# Changes here will be overwritten by Copier; NEVER edit this file manually.
_commit: template/v1.55.14
_rubio_template_version: template/v1.55.14
_src_path: https://github.com/Rubio-Enterprises/standards.git
archetype: go-cli
default_branch: main
has_codex_plugin: false
has_e2e: true
has_embedded_web: false
has_go: true
has_javascript: false
has_lint_hooks: true
has_python: false
has_rust: false
has_swift: false
has_test: false
has_typescript: false
is_fork: true
is_public: true
node_version: 22.12.0
project_name: mo
tier: experimental
upstream_branch: main
upstream_url: https://github.com/k1LoW/mo
uses_release_please: false
